#git push origin feature/exploring-workflow

name: Solar-system-workflow

on: 
  workflow_dispatch: 
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI : 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
  DOCKERHUB_USERNAME: ${{vars.DOCKERHUB_USERNAME}}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_ECR_ROLE: ${{ secrets.AWS_ECR_ROLE}}
  
jobs:
  testing:
    name: unit testing

  # Adding service conatainer so that all tested happen in that db container instead of production database
    services:
      mongodb:
        image: siddharth67/mongo-db:non-prod
        ports:
          - 27017:27017
    env:
      MONGO_URI: 'mongodb://localhost:27017/superData'
      MONGO_USERNAME: non-prod-user
      MONGO_PASSWORD: non-prod-password 

    strategy:
      matrix:
        operating_system: [ubuntu-latest] # Abhi ke liye macos-latest  hatta dete h ko
        versions: [18, 20]
        # exclude:
        #   - operating_system: macos-latest
        #     versions: 18
    runs-on: ${{matrix.operating_system}}
    steps:
    - name: checkout Repository
      uses: actions/checkout@v4

    - name: Nodejs setup
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.versions}}
    
    - name: Cache npm dependences
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{runner.os}}-node_modules-${{ hashFiles('package-lock.json') }}
      

    - name: Install Dependencies
      run: npm install
    
    - name: Unit test
      id: nodejs-test
      run : npm test

    - name: Archieve Result
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: Mocha-Test-Result
        path: test-results.xml


  code-coverage:
    name: CodeCoverage
  #  https://docs.github.com/en/actions/how-tos/write-workflows/choose-where-workflows-run/run-jobs-in-a-container
  # https://docs.github.com/en/actions/tutorials/use-containerized-services/create-postgresql-service-containers#running-jobs-in-containers
    container:
      image: node:20

    services:
      mongodb:
        image: siddharth67/mongo-db:non-prod
      # here no need of ports because in one job two container {job and service }are running that means they can talk each other via default network we can use label
        options: 
          --name mongo
        # ports:
        #   - 27017:27017
    env:
      MONGO_URI: 'mongodb://mongo:27017/superData' # yeh label hum mongo yaha put krnge 
      MONGO_USERNAME: non-prod-user
      MONGO_PASSWORD: non-prod-password 

    runs-on: ubuntu-latest
    steps:
    - name: checkout Repository
      uses: actions/checkout@v4

    # - name: Nodejs setup
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: 18

    - name: Cache npm dependences
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{runner.os}}-node_modules-${{ hashFiles('package-lock.json') }}
    
    - name: Install Dependencies
      run: npm install
    
    - name: Check run coverage
      continue-on-error: true
      run : npm run coverage

    - name: Archieve Result
      uses: actions/upload-artifact@v7
      with:
        name: Code-Coverage-Result
        path: coverage
        retention-days: 5


  docker:
    name: Containeraize  
    needs: [ testing, code-coverage ]
    # PERMISSION DENA HOGA job level me GHCR ME PACAKGE JAHA TUMAHARA IMAGE JYEGA WARNA GITHUB TOKEN ERROR DEGA [DENIED KA ] . 
    # bydefault = read hota h , hame write bhi dena hoga 

    permissions:
      contents: read
      packages: write
      id-token: write # yeh hamne ecr ke liye kiya h write

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo.
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
# ab wahi image ko hum  github container registry me add krnge {https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry}
    - name: Login to GHCR Hub
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN}}

# Debug OIDC tOKEN
    - name: Debug OIDC Token
      run: |
        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
        "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | \
        jq -R 'split(".") | .[1] | @base64d | fromjson'   

# yeh hum ECR me bhi push krna chahte h 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ECR_ROLE }}
        aws-region: us-east-1

    # login to ecr
    - name: Login to Amazon ECR
      id: ecr-login # login id kaam aayega output me put krne ke liye
      uses: aws-actions/amazon-ecr-login@v2

    - name: docker build for testing
      uses: docker/build-push-action@v6
      with:
        context: .                                    # Dockerfile kahan hai (root)
        push: false                                   # build ke baad push bhi karo and false for not push to hub
        tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

    - name: testing the image
      run: |
        docker images
        docker run --name solar-app -p 3000:3000 -d \
            -e MONGO_URI=$MONGO_URI \
            -e MONGO_USERNAME=$MONGO_USERNAME \
            -e MONGO_PASSWORD=$MONGO_PASSWORD \
            ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
        export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
        echo $IP

        echo Testing Image URL using wget
        wget -q -O - 127.0.0.1:3000/live | grep live

# publish image 
    - name: Publish image in dockerhub and GHCR
      uses: docker/build-push-action@v6
      with:
        context: .                                    # Dockerfile kahan hai (root)
        push: true                                 # build ke baad push bhi karo and false for not push to hub
        tags: | 
          ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
          ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}
          ${{ steps.ecr-login.outputs.registry }}/solar-system:${{ github.sha }}

  dev-deploy:
    if: contains(github.ref, 'feature/')
    needs: docker
    uses: ./.github/workflows/reuse-deployment.yaml
    secrets:
      mongo-uri: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
      mongodb:  ${{secrets.MONGO_PASSWORD}}
    #Agr hum reusable workflows krte h toh iss solar-system ko hum Caller bolte h aur reusable file ko Called.
    
  integration-testing:
    name: Dev Integration Testing
    if: contains(github.ref, 'feature/')
    needs: dev-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Test URL Output using CURL and JQ
        run: |
          URL="solar-system-${{ vars.NAMESPACE }}.${{ vars.INGRESS_IP }}.nip.io"
          echo "Testing URL: $URL"
          echo "-----------------------------------"
          curl -s http://$URL/live | jq -r .status | grep -i live

  production-deploy:
    if: github.ref == 'refs/heads/main'
    needs: docker
    uses: ./.github/workflows/reuse-deployment.yaml
    secrets:
      mongo-uri: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
      mongodb:  ${{secrets.MONGO_PASSWORD}}
    # Github enviroment
    # environment: 
    #   name: production
    #   url: solar-system-${{ vars.PROD_NAMESPACE }}.${{ vars.INGRESS_IP }}.nip.io
    # runs-on: ubuntu-latest
    # steps:
    #  - name: checkout Repository
    #    uses: actions/checkout@v4

    #  - name: Install k8s cli
    #    uses: azure/setup-kubectl@v4
    
    #  - name: Set Kubeconfig context
    #    uses: azure/k8s-set-context@v4
    #    with:
    #      method: kubeconfig
    #      kubeconfig: ${{ vars.KUBECONFIG }}

    #  - name: Checking k8s versions and nodes
    #    run: |
    #      kubectl version --client
    #      echo "---------------------------------"
    #      kubectl get nodes
    #   # Replace placeholder
    #  - name: Save Ingress Controller IP as a GITHUB Environment Variable
    #    run: |
    #      echo "INGRESS_IP=${{ vars.INGRESS_IP }}" >> $GITHUB_ENV
    #  - name: Replace Placeholders / Tokens
    #    uses: cschleiden/replace-tokens@v1
    #    with:
    #      tokenPrefix: '${'
    #      tokenSuffix: '}'
    #      files: '["kubernetes/production/*.yaml"]'
    #    env:
    #     NAMESPACE: ${{vars.PROD_NAMESPACE}}
    #     K8S_IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
    #     REPLICAS: ${{vars.REPLICAS}}
    #     INGRESS_IP: ${{env.INGRESS_IP}}
    
    #  - name: Check the files
    #    run: |
    #      cat kubernetes/production/*.yaml
    #  - name: Create MongoDB Secret
    #    run: |
    #     kubectl create namespace ${{ vars.PROD_NAMESPACE}} --dry-run=client -o yaml | kubectl apply -f -
    #     kubectl -n ${{ vars.PROD_NAMESPACE}} create secret generic mongo-db-creds \
    #       --from-literal=MONGO_URI='${{ env.MONGO_URI }}' \
    #       --from-literal=MONGO_USERNAME='${{ vars.MONGO_USERNAME }}' \
    #       --from-literal=MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' \
    #       --save-config \
    #       --dry-run=client \
    #       -o yaml | kubectl apply -f -
    #  - name: deploy in Prod
    #    run: | 
    #     kubectl apply -f kubernetes/production
    
    #  - name: Set App Ingress Host URL
    #    id: set-ingress-host
    #    run: |
    #     HOST=$(kubectl -n ${{ vars.PROD_NAMESPACE }} get ingress solar-system -o jsonpath="{.spec.rules[0].host}")
    #     echo "APP_INGRESS_HOST=$HOST" >> $GITHUB_ENV
    #     echo "app_host=$HOST" >> $GITHUB_OUTPUT

  # prod-integration-testing:
    name: prod Integration Testing
    if: github.ref == 'refs/heads/main'
    needs: production-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Test URL Output using CURL and JQ
        run: |
          sleep 20
          URL="solar-system-${{ vars.PROD_NAMESPACE }}.${{ vars.INGRESS_IP }}.nip.io"
          echo "Testing URL: $URL"
          echo "-----------------------------------"
          curl -s http://$URL/live | jq -r .status | grep -i live      
    



    